# Configuration for load and tpcc script

tpcc_user: tpcc
tpcc_password: tpcc
tpcc_url: jdbc:oracle:thin:@192.168.1.5:1521:XE
warehouse_range: 1..3

think_time: # Think time
  new_order:    0.01  # New-Order
  payment:      0.01  # Payment
  order_status: 0.01  # Order-Status
  delivery:     0.01  # Delivery
  stock_level:  0.01  # Stock-Level

tx_percentage: # Percentage of each transaction
  new_order:    45.0  # New-Order
  payment:      43.0  # Payment
  order_status:  4.0  # Order-Status
  delivery:      4.0  # Delivery
  stock_level:   4.0  # Stock-Level
