# Configuration for load and tpcc script

tpcc_user: tpcc
tpcc_password: tpcc
tpcc_url: jdbc:oracle:thin:@192.168.1.5:1521:XE
warehouse_range: 1..3

tx_percentage: # Percentage of each transaction
  New-Order:    45.0
  Payment:      43.0
  Order-Status:  4.0
  Delivery:      4.0
  Stock-Level:   4.0

think_time: # Think time (in seconds)
  New-Order:    0.01
  Payment:      0.01
  Order-Status: 0.01
  Delivery:     0.01
  Stock-Level:  0.01
