# Configuration for load and tpcc script

tpcc_user: tpcc
tpcc_password: tpcc
tpcc_url: jdbc:oracle:thin:@192.168.1.5:1521:XE
warehouse_range: 1..3

think_time: 0.01
tx_percentage: # Percentage of each transaction
    - 45.0     # New-Order
    - 43.0     # Payment
    -  4.0     # Order-Status
    -  4.0     # Delivery
    -  4.0     # Stock-Level
