# Configuration for setup, load, teardown and tpcc script

tpcc_user: tpcc
tpcc_password: tpcc
tpcc_url: jdbc:oracle:thin:@//192.168.1.5:1521/XE
warehouse_range: 1..3

tx_percentage: # Percentage of each transaction
  New-Order:    45.0
  Payment:      43.0
  Order-Status:  4.0
  Delivery:      4.0
  Stock-Level:   4.0

keying_time: # Keying Time (in seconds)
  New-Order:    18.00
  Payment:       3.00
  Order-Status:  2.00
  Delivery:      2.00
  Stock-Level:   2.00

think_time: # Think Time (in seconds)
  New-Order:    12.00
  Payment:      12.00
  Order-Status: 10.00
  Delivery:      5.00
  Stock-Level:   5.00

avoid_deadlock: true
get_connection_everytime: false
use_bind_variables: true
statement_cache_size: 50
log_level: info                # off | fatal | error | warn | info | debug | all

setup:
  table_tablespace: USERS
  index_tablespace: USERS
  partition_count: 3
  parallel_degree: 3
  loading_only: false

remote:
  - 192.168.1.6:9000
  - 192.168.1.7:9000
  - 192.168.1.8:9000
