# Configuration for setup and teardown script

SETUP_LOG=$TPCB_HOME/log/setup.log
TEARDOWN_LOG=$TPCB_HOME/log/teardown.log

TPCB_USER=tpcb
TPCB_PASSWORD=tpcb
TPCB_TNSNAME=XE

ACCOUNT_TABLESPACE=USERS
TELLER_TABLESPACE=USERS
BRANCH_TABLESPACE=USERS
HISTORY_TABLESPACE=USERS

ACCOUNT_INDEX_TABLESPACE=USERS
TELLER_INDEX_TABLESPACE=USERS
BRANCH_INDEX_TABLESPACE=USERS

RTACTL=$TPCB_HOME/../../bin/rtactl
PARALLEL_LOAD_DEGREE=5
RTA_PORT=9000
