# Configuration for load and tpcb script

tpcb_user: tpcb
tpcb_password: tpcb
tpcb_url: jdbc:oracle:thin:@//192.168.1.5:1521/XE
branch_range: 1..3

log_level: info                # off | fatal | error | warn | info | debug | all
